#!/bin/bash
set -euxo pipefail

apt-get update -y
apt-get install -y ruby-full wget

cd /tmp
wget https://aws-codedeploy-us-west-2.s3.us-west-2.amazonaws.com/latest/install
chmod +x ./install
./install auto

echo ":region: us-west-2" >> /etc/codedeploy-agent/conf/codedeployagent.yml

systemctl enable codedeploy-agent
systemctl restart codedeploy-agent

mkdir -p /var/www/html
